defaults:
  - strategy: single_device
  - loggers:
      - csv
  - callbacks:
      - pprint_batch
      - pprint_model_stats
      - export_module
  - _self_

_target_: vod_exps.init.fabric
accelerator: auto
devices: ${resources.n_devices}
precision: 32
