encoder:
  name_or_path: ${encoder_name}
  max_length: 200
  use_fast: true
  padding_side: right
  truncation_side: right
  # Kwargs
  add_special_tokens: true
  padding: max_length
  truncation: true
lm:
  name_or_path: ${lm_name}
  max_length: 512
  use_fast: true
  padding_side: left
  truncation_side: left
  # Kwargs
  add_special_tokens: false
  padding: max_length
  truncation: true
