version: 2.1

orbs:
  slack: circleci/slack@3.4.2
  gimlet: gimlet-io/circleci-orb@4.0.0

workflows:
  build:
    jobs:
      - test:
          context:
            - AzureCR
            - Slack
            - DSGithub

      - bump_version:
          context:
            - DSGithub

          requires:
            - test

          filters:
            branches:
              only:
                - main


jobs:
  test:
    docker:
      - image: cimg/python:3.11.2

    steps:
      - setup_remote_docker
      - checkout

      - run:
          name: Install dependency packages
          command: |
            poetry install

      - run:
          name: Lint
          command: |
            make lint

      - run:
          name: Test
          command: |
            make test

      - slack/status:
          fail_only: true
          only_for_branches: main
          channel: tech-data-science-alerts

  bump_version:
    docker:
      - image: cimg/python:3.11.2

    steps:
      - setup_remote_docker
      - checkout

      - run:
          name: Bump version
          command: |
            git config --global user.email "hal9000@raffle.ai"
            git config --global user.name "Hal 9000"
            git remote set-url origin https://$GIT_TOKEN@github.com/raffle-ai/ds-research.git/

            python3 -m venv venv
            source venv/bin/activate
            pip install commitizen
            git pull
            cz bump --changelog

            git push origin main
            git push origin --tags