defaults:
  - search_defaults: default
  - options: default
  - _self_

# Base search
search:
  dense:
    backend: faiss
    factory: IVFauto,PQ32x8
    train_size: 1_000_000
    nprobe: 32
  sparse:
    backend: elasticsearch

# Train/val splits
training:
  queries:
    train:
      - identifier: msmarco_train
        name_or_path:
          _target_: vod_datasets.BeirDatasetLoader
          what: queries
        subsets: msmarco
        split: train
        link: msmarco_sections
    val:
      - identifier: msmarco_validation
        name_or_path:
          _target_: vod_datasets.BeirDatasetLoader
          what: queries
        subsets: msmarco
        split: validation
        link: msmarco_sections

  sections:
    - identifier: msmarco_sections
      name_or_path:
        _target_: vod_datasets.BeirDatasetLoader
        what: sections
      subsets: msmarco

# Benchmarks
benchmark:
  - queries:
      identifier: msmarco_validation
      name_or_path:
        _target_: vod_datasets.BeirDatasetLoader
        what: queries
      subsets: msmarco
      split: validation
      link: msmarco_sections

    sections:
      identifier: msmarco_sections
      name_or_path:
        _target_: vod_datasets.BeirDatasetLoader
        what: sections
      subsets: msmarco

      # # Note -- you can override the default search backend for a specific dataset/benchmark
      # search:
      #   dense:
      #     backend: faiss
      #     factory: IVFauto,Flat
      #     gpu:
      #       use:_float16: true
