_target_: vod_models.VodBertEncoderDebug.from_pretrained
pretrained_model_name_or_path: google/bert_uncased_L-4_H-256_A-4
pooler:
  _target_: builtins.dict
  projection_size: null
  output_activation: null
  output_norm: null
  agg_method: cls
  scaler: 1.0

