# see https://pytorch-optimizer.readthedocs.io/en/latest/_modules/torch_optimizer/adafactor.html
defaults:
  - base

_target_: torch_optimizer.Adafactor
_partial_: true
scale_parameter: false
relative_step: false
