_target_: vod_exps.init.fsdp_strategy
cpu_offload: false
mixed_precision: null
auto_wrap_policy: null
sharding_strategy: null
activation_checkpointing: null
state_dict_type: sharded
timeout: 7_200 # 2hours
